#!/bin/bash
message1="\n\nBenvenuto al livello 1 di Tux's game, il gioco per imparare l'uso del terminale Linux.\nLo scopo del livello è trovare la password dell'utente2, contenuta nel file utente2_pwd.txt.\nEcco i comandi utili al raggiungimento dell'obiettivo:\nman -> il manuale dei comandi Linux (digita 'man nome_comando' per visualizzare le opzioni di quel comando)\npwd -> mostra la posizione in cui ti trovi dandoti il percorso\nls -> elenca il contenuto della directory in cui ti trovi\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file."
message2="\n\nLivello 2, lo scopo è trovare il file .utente3_pwd.txt, il file è contenuto nella cartella data ma è un file nascosto.\nI file nascosti in Linux sono file che iniziano con un punto (.) nel loro nome, come ad esempio ".file_nascosto".\nQuesti file sono detti "nascosti" perché non vengono visualizzati quando si elenca il contenuto di una directory utilizzando il comando "ls" a meno che non venga specificata un'opzione per mostrarli esplicitamente.\nComandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\npwd -> mostra la posizione in cui ti trovi dandoti il percorso\nls -> elenca il contenuto della directory in cui ti trovi\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file"
message3="\n\nLivello 3, l'obiettivo è trovare il file utente4_pwd.txt, il file è contenuto dentro a una serie di cartelle. Per trovare la sua esatta locazione, puoi usare il comando find.\nComandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file\nfind -> comando che permette di visualizzare la posizione di un file o cartella o contenuto (digita man find per visualizzare le opzioni di utilizzo)"
message4="\n\nLivello 4, per passare al livello successivo l'utente deve trovare la password contenuta nel file utente5_pwd.txt, attenzione però, il file contiene molte stringhe casuali e non sarà facile trovare la password. Avrai bisogno di filtrare il contenuto del file, potresti avere bisogno di usare la combinazione di più comandi per farlo. Puoi usare il simbolo '|' che prende il risultato del comando alla sua sinistra e lo passa al comando alla sua destra. Ad esempio: ls | grep 'nome_file'.\nComandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\npwd -> mostra la posizione in cui ti trovi dandoti il percorso\nls -> elenca il contenuto della directory in cui ti trovi\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file\ngrep -> comando per cercare l'esatta corrispondenza, usato per filtrare le ricerche."
message5="\n\nLivello 5, ci sono 2 file, il file utente6_pwd_old.txt e il file utente6_pwd_new.txt. La password è contenuta nel file utente6_pwd_new.txt ed è l'unica riga diversa tra il file old e il nuovo. Comandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\nls -> elenca il contenuto della directory in cui ti trovi\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file\ndiff -> comando che, dati due file, mostra la differenza tra essi ('man diff' per visualizzare le opzioni)."
message6="\n\nLivello 6, il file utente7_pwd.txt non esiste, crea il file utente7_pwd.txt vuoto all'interno del percorso '/home/utente6/data/secrets/utente7_secret/' e digita il comando 'done'. Questo comando personalizzato avvierà un controllo sulla presenza del file e scriverà la password al suo interno.\nComandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\nls -> elenca il contenuto della directory in cui ti trovi\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file\ntouch -> comando per creare un file."
message7="\n\nLivello 7, il file 'utente8_pwd.txt' è contenuto dentro ad un archivio.zip. Dovrai decomprimere l'archivio e cercare il file al suo interno.\nComandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\nls -> elenca il contenuto della directory in cui ti trovi\ncd -> comando utile per spostarsi tra le directory\ncat -> stampare a terminale il contenuto di un file\ntar -> comandi per gestire gli archivi zip ('man tar' per vedere le opzioni di utilizzo)."
message8="\n\nLivello 8, il file utente9_pwd.txt è contenuto all'interno di un archivio zip. Una volta decompresso l'archivio, troverai il file, ma attenzione: il file è in formato esadecimale e dovrai riportarlo al formato originale per poter leggere la password.\nComandi utili:\nman -> il manuale dei comandi Linux (digita 'man 'nome comando'' per visualizzare le opzioni di quel comando)\ntar -> comandi per gestire gli archivi zip ('man tar' per vedere le opzioni di utilizzo)\nxxd -> comando usato per manipolaree convertire dati binari,ottali,esadecimali."
message9="\n\n DIVENTA ROOT ! tu puoi farlo! :)"

echo "echo -e \"$message1\"" >> /home/utente1/.bashrc
echo "echo -e \"$message2\"" >> /home/utente2/.bashrc
echo "echo -e \"$message3\"" >> /home/utente3/.bashrc
echo "echo -e \"$message4\"" >> /home/utente4/.bashrc
echo "echo -e \"$message5\"" >> /home/utente5/.bashrc
echo "echo -e \"$message6\"" >> /home/utente6/.bashrc
echo -e "alias done='bash /route.sh'" >> /home/utente6/.bashrc 
echo "echo -e \"$message7\"" >> /home/utente7/.bashrc
echo "echo -e \"$message8\"" >> /home/utente8/.bashrc
echo "echo -e \"$message9\"" >> /home/utente9/.bashrc
echo "echo -e \"$message10\"" >> root/.bashrc



#echo "echo -e '$message1'" >> /home/utente1/.bashrc

